title: "Sher Li Oh"
description: "Computational Biology | Neuroscience"
theme: jekyll-theme-minimal

author: "Sher Li Oh"
github_username: ohsherli
linkedin: sher-li-oh

# Optional: show navigation links
show_downloads: false
